@baseUrl = https://api.trello.com

### authorization keys (do not commit)
@key =
@token =

### get boards
# @name getBoards
GET {{baseUrl}}/1/members/me/boards
    ?key={{key}}
    &token={{token}}

@board1 = {{getBoards.response.body.$[1].id}}

### get lists
# @name getLists
GET {{baseUrl}}/1/boards/{{board1}}/lists
    ?key={{key}}
    &token={{token}}

@list0 = {{getLists.response.body.$[0].id}}
@card1 = {{getLists.response.body.$[1].id}}

### get cards
# @name getCards
GET {{baseUrl}}/1/lists/{{list0}}/cards
    ?key={{key}}
    &token={{token}}

### get card by id
# @name getCard
GET {{baseUrl}}/1/lists/{{card1}}/cards
    ?key={{key}}
    &token={{token}}
