@baseUrl = https://api.trello.com

### authorization keys
@key =
@token =
@secret =
@auth =

@board1 = {{getBoards.response.body.$[1].id}}
@board2 = {{getBoards.response.body.$[0].id}}

@list1 = {{getLists.response.body.$[0].id}}
@cardDoing = {{getLists.response.body.$[1].id}}

### get boards

GET https://api.trello.com/1/members/me/boards
    ?key={{key}}
    &token={{token}}

### get boards 2
# @name getBoards
GET {{baseUrl}}/1/members/me/boards
    ?{{auth}}

### search (Error: not logged in)
GET {{baseUrl}}/1/search?query=test
    ?{{auth}}

### get lists
# @name getLists
GET {{baseUrl}}/1/boards/{{board1}}/lists
    ?{{auth}}

### get cards
# @name getCards
GET {{baseUrl}}/1/lists/{{list1}}/cards
    ?{{auth}}

### get card by id
# @name getCard
GET {{baseUrl}}/1/lists/{{cardDoing}}/cards
    ?{{auth}}
